### ISSUE TITLE
[Get] /User/Me - 500 Internal Server Error

### ISSUE THREAD

**Issue by w7rus** [techiedesu/MusicPlayerBackend#7]
Logs:

```
[15:05:12 ERR] Connection id "0HN14HPGKBEFE", Request id "0HN14HPGKBEFE:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: Endpoint MusicPlayerBackend.Controllers.UserController.Me (MusicPlayerBackend) contains authorization metadata, but a middleware was not found that supports authorization.
Configure your application startup by adding app.UseAuthorization() in the application startup code. If there are calls to app.UseRouting() and app.UseEndpoints(...), the call to app.UseAuthorization() must go between them.
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.ThrowMissingAuthMiddlewareException(Endpoint endpoint)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at MusicPlayerBackend.App.Middlewares.UnauthorizedMiddleware.InvokeAsync(HttpContext context) in /home/w7rus/Documents/Projects/not-spotify-backend/Src/MusicPlayerBackend/App/Middlewares/UnauthorizedMiddleware.cs:line 13
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   ```

**Comment by techiedesu** [comment]
Работает в 848506312eba4beefa5921f8c2b8d28df38dda3e
